# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

filter_task:
  description: >
    Analyze the provided emails and create a summary of important messages. Identify key topics, urgent matters, and filter out promotional content. 
    Emails: {emails}
    
  agent: email_filter_agent
  expected_output: "A comprehensive summary of today's important emails, organized by priority and topic."
    
draft_emails_task:
  description: >
    Using the following information:
    Company Information: {company_info}
    Customer List: {customers}
    
    Create personalized email drafts for each customer in the list.
    For each customer:
    1. Consider their specific business description
    2. Highlight how the company platform can benefit their business
    3. Make reference to their specific workshop offerings
    4. Keep the tone professional but friendly
    5. Include a clear call to action
    
    Return the output as a JSON array where each email draft is an object with this structure (example):
    [
      {{
        "to": "customer_email",
        "subject": "email_subject",
        "body": "email_content"
      }}
    ]
  agent: email_draft_agent
  expected_output: "A JSON array of email draft objects"
    
respond_to_emails_task:
  description: >
    Respond to the provided emails. Be friendly and nice, and stay professional. Don't respond to promotions and adds.  
    Emails: {emails}
  agent: email_response_agent
  expected_output: >
    A JSON array of email response objects
    The output should be a JSON array where each email response is an object with this structure (example):
    [
      {{
        "to": "sender_email",
        "subject": "email_subject",
        "body": "email_content"
      }}
    ]

